module WelcomeHelper
  def list_of_region
    [
      "Aberdeenshire",
      "Adur",
      "Allerdale",
      "Amber Valley",
      "Angus",
      "Antrim and Newtownabbey",
      "Argyll and Bute",
      "Armagh Banbridge and Craigavon",
      "Arun",
      "Ashfield",
      "Ashford",
      "Aylesbury Vale",
      "Babergh",
      "Barking and Dagenham",
      "Barnet",
      "Barnsley",
      "Barrow-in-Furness",
      "Basildon",
      "Basingstoke and Deane",
      "Bassetlaw",
      "Bath and North East Somerset",
      "Bedford",
      "Belfast",
      "Bexley",
      "Birmingham",
      "Blaby",
      "Blackburn with Darwen",
      "Blackpool",
      "Blaenau Gwent",
      "Bolsover",
      "Bolton",
      "Boston",
      "Bournemouth",
      "Bracknell Forest",
      "Bradford",
      "Braintree",
      "Breckland",
      "Brent",
      "Brentwood",
      "Bridgend",
      "Brighton and Hove",
      "Broadland",
      "Bromley",
      "Bromsgrove",
      "Broxbourne",
      "Broxtowe",
      "Buckinghamshire",
      "Burnley",
      "Bury",
      "Caerphilly",
      "Calderdale",
      "Cambridge",
      "Cambridgeshire",
      "Camden",
      "Cannock Chase",
      "Canterbury",
      "Cardiff",
      "Carlisle",
      "Carmarthenshire",
      "Castle Point",
      "Causeway Coast and Glens",
      "Central Bedfordshire",
      "Ceredigion",
      "Charnwood",
      "Chelmsford",
      "Cheltenham",
      "Cherwell",
      "Cheshire East",
      "Cheshire West and Chester",
      "Chesterfield",
      "Chichester",
      "Chiltern",
      "Chorley",
      "Christchurch",
      "City of Aberdeen",
      "City of Bristol",
      "City of Derby",
      "City of Dundee",
      "City of Edinburgh",
      "City of Glasgow",
      "City of Kingston upon Hull",
      "City of London",
      "City of Nottingham",
      "City of Peterborough",
      "City of Plymouth",
      "City of Westminster",
      "Clackmannanshire",
      "Colchester",
      "Conwy",
      "Copeland",
      "Corby",
      "Cornwall",
      "Cotswold",
      "County Durham",
      "Coventry",
      "Craven",
      "Crawley",
      "Croydon",
      "Cumbria",
      "Dacorum",
      "Darlington",
      "Dartford",
      "Daventry",
      "Denbighshire",
      "Derbyshire",
      "Derbyshire Dales",
      "Derry and Strabane",
      "Devon",
      "Doncaster",
      "Dorset",
      "Dover",
      "Dudley",
      "Dumfries and Galloway",
      "Ealing",
      "East Ayrshire",
      "East Cambridgeshire",
      "East Devon",
      "East Dorset",
      "East Dunbartonshire",
      "East Hampshire",
      "East Hertfordshire",
      "East Lindsey",
      "East Lothian",
      "East Midlands",
      "East Northamptonshire",
      "East Renfrewshire",
      "East Riding of Yorkshire",
      "East Staffordshire",
      "East Sussex",
      "East of England",
      "Eastbourne",
      "Eastleigh",
      "Eden",
      "Elmbridge",
      "Enfield",
      "England",
      "England and Wales",
      "Epping Forest",
      "Epsom and Ewell",
      "Erewash",
      "Essex",
      "Exeter",
      "Falkirk",
      "Fareham",
      "Fenland",
      "Fermanagh and Omagh",
      "Fife",
      "Flintshire",
      "Forest Heath",
      "Forest of Dean",
      "Fylde",
      "Gateshead",
      "Gedling",
      "Gloucester",
      "Gloucestershire",
      "Gosport",
      "Gravesham",
      "Great Britain",
      "Great Yarmouth",
      "Greater Manchester",
      "Greenwich",
      "Guildford",
      "Gwynedd",
      "Hackney",
      "Halton",
      "Hambleton",
      "Hammersmith and Fulham",
      "Hampshire",
      "Harborough",
      "Haringey",
      "Harlow",
      "Harrogate",
      "Harrow",
      "Hart",
      "Hartlepool",
      "Hastings",
      "Havant",
      "Havering",
      "Herefordshire",
      "Hertfordshire",
      "Hertsmere",
      "High Peak",
      "Highland",
      "Hillingdon",
      "Hinckley and Bosworth",
      "Horsham",
      "Hounslow",
      "Huntingdonshire",
      "Hyndburn",
      "Inner London",
      "Inverclyde",
      "Ipswich",
      "Isle of Anglesey",
      "Isle of Wight",
      "Islington",
      "Kensington And Chelsea",
      "Kent",
      "Kettering",
      "King's Lynn and West Norfolk ",
      "Kingston upon Thames",
      "Kirklees",
      "Knowsley",
      "Lambeth",
      "Lancashire",
      "Lancaster",
      "Leeds",
      "Leicester",
      "Leicestershire",
      "Lewes",
      "Lewisham",
      "Lichfield",
      "Lincoln",
      "Lincolnshire",
      "Lisburn and Castlereagh",
      "Liverpool",
      "London",
      "Luton",
      "Maidstone",
      "Maldon",
      "Malvern Hills",
      "Manchester",
      "Mansfield",
      "Medway",
      "Melton",
      "Mendip",
      "Merseyside",
      "Merthyr Tydfil",
      "Merton",
      "Mid Devon",
      "Mid Suffolk",
      "Mid Sussex",
      "Mid Ulster",
      "Mid and East Antrim",
      "Middlesbrough",
      "Midlothian",
      "Milton Keynes",
      "Mole Valley",
      "Monmouthshire",
      "Moray",
      "Na h-Eileanan Siar",
      "Neath Port Talbot",
      "New Forest",
      "Newark and Sherwood",
      "Newcastle upon Tyne",
      "Newcastle-under-Lyme",
      "Newham",
      "Newport",
      "Newry Mourne and Down",
      "Norfolk",
      "North Ayrshire",
      "North Devon",
      "North Dorset",
      "North Down and Ards",
      "North East",
      "North East Derbyshire",
      "North East Lincolnshire",
      "North Hertfordshire",
      "North Kesteven",
      "North Lanarkshire",
      "North Lincolnshire",
      "North Norfolk",
      "North Somerset",
      "North Tyneside",
      "North Warwickshire",
      "North West",
      "North West Leicestershire",
      "North Yorkshire",
      "Northampton",
      "Northamptonshire",
      "Northern Ireland",
      "Northumberland",
      "Norwich",
      "Nottinghamshire",
      "Nuneaton and Bedworth",
      "Oadby and Wigston",
      "Oldham",
      "Orkney Islands",
      "Outer London",
      "Oxford",
      "Oxfordshire",
      "Pembrokeshire",
      "Pendle",
      "Perth and Kinross",
      "Poole",
      "Portsmouth",
      "Powys",
      "Preston",
      "Purbeck",
      "Reading",
      "Redbridge",
      "Redcar and Cleveland",
      "Redditch",
      "Reigate and Banstead",
      "Renfrewshire",
      "Rhondda Cynon Taf",
      "Ribble Valley",
      "Richmond upon Thames",
      "Richmondshire",
      "Rochdale",
      "Rochford",
      "Rossendale",
      "Rother",
      "Rotherham",
      "Rugby",
      "Runnymede",
      "Rushcliffe",
      "Rushmoor",
      "Rutland",
      "Ryedale",
      "Salford",
      "Sandwell",
      "Scarborough",
      "Scotland",
      "Scottish Borders",
      "Sedgemoor",
      "Sefton",
      "Selby",
      "Sevenoaks",
      "Sheffield",
      "Shepway",
      "Shetland Islands",
      "Shropshire",
      "Slough",
      "Solihull",
      "Somerset",
      "South Ayrshire",
      "South Bucks",
      "South Cambridgeshire",
      "South Derbyshire",
      "South East",
      "South Gloucestershire",
      "South Hams",
      "South Holland",
      "South Kesteven",
      "South Lakeland",
      "South Lanarkshire",
      "South Norfolk",
      "South Northamptonshire",
      "South Oxfordshire",
      "South Ribble",
      "South Somerset",
      "South Staffordshire",
      "South Tyneside",
      "South West",
      "South Yorkshire",
      "Southampton",
      "Southend-on-Sea",
      "Southwark",
      "Spelthorne",
      "St Albans",
      "St Edmundsbury",
      "St Helens",
      "Stafford",
      "Staffordshire",
      "Staffordshire Moorlands",
      "Stevenage",
      "Stirling",
      "Stockport",
      "Stockton-on-Tees",
      "Stoke-on-Trent",
      "Stratford-on-Avon",
      "Stroud",
      "Suffolk",
      "Suffolk Coastal",
      "Sunderland",
      "Surrey",
      "Surrey Heath",
      "Sutton",
      "Swale",
      "Swansea",
      "Swindon",
      "Tameside",
      "Tamworth",
      "Tandridge",
      "Taunton Deane",
      "Teignbridge",
      "Telford and Wrekin",
      "Tendring",
      "Test Valley",
      "Tewkesbury",
      "Thanet",
      "Three Rivers",
      "Thurrock",
      "Tonbridge and Malling",
      "Torbay",
      "Torfaen",
      "Torridge",
      "Tower Hamlets",
      "Trafford",
      "Tunbridge Wells",
      "Tyne and Wear",
      "United Kingdom",
      "Uttlesford",
      "Vale of Glamorgan",
      "Vale of White Horse",
      "Wakefield",
      "Wales",
      "Walsall",
      "Waltham Forest",
      "Wandsworth",
      "Warrington",
      "Warwick",
      "Warwickshire",
      "Watford",
      "Waveney",
      "Waverley",
      "Wealden",
      "Wellingborough",
      "Welwyn Hatfield",
      "West Berkshire",
      "West Devon",
      "West Dorset",
      "West Dunbartonshire",
      "West Lancashire",
      "West Lindsey",
      "West Lothian",
      "West Midlands",
      "West Midlands Region",
      "West Oxfordshire",
      "West Somerset",
      "West Sussex",
      "West Yorkshire",
      "Weymouth and Portland",
      "Wigan",
      "Wiltshire",
      "Winchester",
      "Windsor and Maidenhead",
      "Wirral",
      "Woking",
      "Wokingham",
      "Wolverhampton",
      "Worcester",
      "Worcestershire",
      "Worthing",
      "Wrexham",
      "Wychavon",
      "Wycombe",
      "Wyre",
      "Wyre Forest",
      "York",
      "Yorkshire and The Humber",
    ]
  end
end
